default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: <%= ENV['RAILS_DATABASE_USER'] %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: bitBot_development

test:
  <<: *default
  database: bitBot_test

  #production:
  #  <<: *default
  #  database: rails_course_production
  #  username: rails_course
  #  password: <%#= ENV['RAILS_COURSE_DATABASE_PASSWORD'] %>